name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - 'ci.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'
  pull_request:
    paths:
      - '**.php'
      - 'ci.yml'
      - 'composer.json'
      - 'phpunit.xml.dist'

jobs:
  ci:
    uses: telegram-bot-sdk/.github/.github/workflows/ci.yml@main
